### PR TITLE
Update information to include GTK 3

### PR DESCRIPTION
**Pull request by vanillajonathan**

### CODE REVIEW

**Comment by wjaguar** [comment]
My thought was, it's too early to claim GTK+3 support, let some testing happen first.
If no horrible bugs get reported, the change of labeling will go into the next version.

**Comment by axredneck** [comment]
@wjaguar
```
/bin/ld: mainwindow.o: in function `setup_language':
mainwindow.c:(.text+0xa87d): undefined reference to `gtk_set_locale'
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:15: mtpaint] Error 1
```
Arch Linux, [my own PKGBUILD](https://aur.archlinux.org/packages/mtpaint-wjaguar) but with gtk3

**Comment by wjaguar** [comment]
@axredneck
>mainwindow.c:(.text+0xa87d): undefined reference to `gtk_set_locale'
Thanks, wrapped it in #if and updated the 3.49.25
Thing is, I do not use internationalization myself and so time at again forget to test the builds with "intl" option. :(

**Comment by axredneck** [comment]
@wjaguar тогда почему не 3.49.25.1 ?

**Comment by axredneck** [comment]
Looks like GTK3 works

**Comment by wjaguar** [comment]
Added all the mentions of GTK+3 to 3.49.26

**Pull request closed without merging**
